GROQ_API_KEY = "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"
QDRANT_API_KEY = "lb4iMzXOBYqmqs8YZlT6ySfNZHWzj6dflKOtyDa10KR250DFbH_txw"
QDRANT_CLIENT_URL = "https://node-0-4802af8f-0f7a-4702-8c23-4e4d614cd411.us-east4-0.gcp.cloud.qdrant.io"